trayectoriaescolar/trayectoriaescolar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trayectoriaescolar/usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('', views.LoginViewAlumno.as_view(), name='login_alumno'),
    path('login_alumno/', views.LoginViewAlumno.as_view(), name='login_alumno'),
    path('administradores', views.lista_admins, name='administradores'),
    path('alumnos', views.lista_alumnos, name='alumnos'),
    path('responsables', views.lista_responsables, name='responsables'),
    path('salir', LogoutView.as_view(), name='logout'),
    path('registro_de_administrador', views.RegistrarAdmin.as_view(),
         name='registro_de_administrador'),
    path('registro_admin_case', views.RegistrarAdminCASE.as_view(),
         name='registro_admin_case'),
    path('registro_alumno', views.RegistrarAlumno.as_view(), name='registro_alumno'),
    path('home', views.home, name='home'),
    path('home_alumno', views.homeAlumno, name='home_alumno'),
    path('registro_responsable', views.RegistrarResponsable.as_view(),
         name='registro_responsable'),
    path('error404', views.error404, name='error404'),
    path('logout', views.signout, name='logout'),
]

trayectoriaescolar/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


class Administradores(User):
    nombre = models.CharField(max_length=100)
    correo = models.CharField(max_length=70)


class Responsables(User):
    nombre = models.TextField(max_length=50, null=False)
    nombre2 = models.TextField(max_length=50, null=True, blank=True)
    apellidoP = models.TextField(max_length=50)
    apellidoM = models.TextField(max_length=50, null=True, blank=True)
    programa_academico = models.TextField(max_length=70, null=False)
    unidad_academica = models.TextField(max_length=50, null=False)


class Alumnos(User):
    nombre = models.TextField(max_length=50, null=False)
    nombre2 = models.TextField(max_length=50, null=True, blank=True)
    apellidoP = models.TextField(max_length=50)
    apellidoM = models.TextField(max_length=50, null=True, blank=True)
    telefono = models.CharField(max_length=10, null=True, blank=True)

trayectoriaescolar/usuarios/forms.py
from django import forms
from usuarios.models import Administradores, Alumnos, Responsables


class UserForm(forms.ModelForm):
    repassword = forms.CharField()

    class Meta:
        model = Administradores
        fields = ('username', 'email', 'password', 'repassword')

    email = forms.EmailField(required=True)

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    def clean_password(self, *args, **kwargs):
        contrasena1 = self.data['password']
        contrasena2 = self.data['repassword']
        if len(contrasena1) < 8:
            raise forms.ValidationError(
                'La contraseña debe contener al menos 8 caracteres')
        if contrasena1.islower():
            raise forms.ValidationError(
                'La contraseña debe contener al menos una letra mayuscula')
        if not any(chr.isalpha() for chr in contrasena1):
            raise forms.ValidationError(
                'La contraseña debe contener al menos una letra')
        if contrasena1.isupper():
            raise forms.ValidationError(
                'La contraseña debe contener al menos una letra minuscula')
        if contrasena1.isalnum():
            raise forms.ValidationError(
                'La contraseña debe contener al menos un caracter especial')
        if not any(chr.isdigit() for chr in contrasena1):
            raise forms.ValidationError(
                'La contraseña debe contener al menos un número')
        if contrasena1 != contrasena2:
            raise forms.ValidationError('Las contraseñas son diferentes')

        return self.data['password']

    def clean_username(self):
        usern = self.cleaned_data['username']
        if len(usern) < 8:
            raise forms.ValidationError(
                'El usuario debe contener 8 o mas caracteres')
        if ' ' in usern:
            raise forms.ValidationError(
                'El nombre de usuario no debe contener espacios')
        if not usern.isalnum():
            raise forms.ValidationError(
                'El nombre de usuario no debe contener caracteres especiales')
        return usern


class FormAdmins(forms.ModelForm):
    class Meta:
        model = Administradores
        fields = '__all__'
        widgets = {
            'usuario': forms.TextInput(attrs={'class': 'form-control'}),
            'correo': forms.TextInput(attrs={'class': 'form-control'}),
        }


class AlumnoForm(forms.ModelForm):
    repassword = forms.CharField()

    class Meta:
        model = Alumnos
        fields = ('username', 'email', 'nombre', 'nombre2', 'apellidoP',
                  'apellidoM', 'telefono', 'password', 'repassword')
    email = forms.EmailField(required=True)

    def save(self, commit=True):
        user = super(AlumnoForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])

        if commit:
            user.save()
        return user

    def clean_username(self):
        matric = self.cleaned_data['username']
        if len(matric) < 8 or len(matric) > 8:
            raise forms.ValidationError(
                'La matrícula debe contener exactamente 8 dígitos')
        if not self.esNumero(matric):
            raise forms.ValidationError(
                'La matrícula debe contener solo números'
            )
        return matric

    def clean_password(self, *args, **kwargs):
        contrasena1 = self.data['password']
        contrasena2 = self.data['repassword']
        if len(contrasena1) < 8:
            raise forms.ValidationError(
                'La contraseña debe contener al menos 8 caracteres')
        if contrasena1.islower():
            raise forms.ValidationError(
                'La contraseña debe contener al menos una letra mayuscula')
        if not any(chr.isalpha() for chr in contrasena1):
            raise forms.ValidationError(
                'La contraseña debe contener al menos una letra')
        if contrasena1.isupper():
            raise forms.ValidationError(
                'La contraseña debe contener al menos una letra minuscula')
        if contrasena1.isalnum():
            raise forms.ValidationError(
                'La contraseña debe contener al menos un caracter especial')
        if not any(chr.isdigit() for chr in contrasena1):
            raise forms.ValidationError(
                'La contraseña debe contener al menos un número')
        if contrasena1 != contrasena2:
            raise forms.ValidationError('Las contraseñas son diferentes')

        return self.data['password']

    def clean_telefono(self):
        tel = self.cleaned_data['telefono']
        if tel != None:
            if not self.esNumero(tel):
                raise forms.ValidationError(
                    'El telefono debe ser un número'
                )
            elif len(tel) != 10:
                raise forms.ValidationError(
                    'El telefono debe ser un número de 10 dígitos'
                )

    def esNumero(self, num):
        try:
            int(num)
            return True
        except:
            return False


class FormAlumnos(forms.ModelForm):
    class Meta:
        model = Alumnos
        fields = '__all__'
        widgets = {
            'matricula': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre2': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidoP': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidoM': forms.TextInput(attrs={'class': 'form-control'}),
            'numero': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ResponsableForm(forms.ModelForm):
    repassword = forms.CharField()

    class Meta:
        model = Responsables
        fields = ('username', 'email', 'nombre', 'nombre2', 'apellidoP', 'apellidoM',
                  'programa_academico', 'unidad_academica', 'password', 'repassword')

    email = forms.EmailField(required=True)

    def save(self, commit=True):
        user = super(ResponsableForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])

        if commit:
            user.save()
        return user

    def clean_password(self, *args, **kwargs):
        contrasena1 = self.data['password']
        contrasena2 = self.data['repassword']
        if len(contrasena1) < 8:
            raise forms.ValidationError(
                'La contraseña debe contener al menos 8 caracteres')
        if contrasena1.islower():
            raise forms.ValidationError(
                'La contraseña debe contener al menos una letra mayuscula')
        if not any(chr.isalpha() for chr in contrasena1):
            raise forms.ValidationError(
                'La contraseña debe contener al menos una letra')
        if contrasena1.isupper():
            raise forms.ValidationError(
                'La contraseña debe contener al menos una letra minuscula')
        if contrasena1.isalnum():
            raise forms.ValidationError(
                'La contraseña debe contener al menos un caracter especial')
        if not any(chr.isdigit() for chr in contrasena1):
            raise forms.ValidationError(
                'La contraseña debe contener al menos un número')
        if contrasena1 != contrasena2:
            raise forms.ValidationError('Las contraseñas son diferentes')

        return self.data['password']

    def clean_username(self):
        usern = self.cleaned_data['username']
        if len(usern) < 8:
            raise forms.ValidationError(
                'El usuario debe contener 8 o mas caracteres')
        if ' ' in usern:
            raise forms.ValidationError(
                'El nombre de usuario no debe contener espacios')
        if not usern.isalnum():
            raise forms.ValidationError(
                'El nombre de usuario no debe contener caracteres especiales')
        return usern


class FormResponsables(forms.ModelForm):
    class Meta:
        model = Alumnos
        fields = '__all__'
        widgets = {
            'matricula': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre2': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidoP': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidoM': forms.TextInput(attrs={'class': 'form-control'}),
            'unidad_academica': forms.TextInput(attrs={'class': 'form-control'}),
            'programa_academico': forms.TextInput(attrs={'class': 'form-control'}),
        }

trayectoriaescolar/usuarios/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from .forms import UserForm, AlumnoForm, ResponsableForm
from .models import Alumnos, Responsables
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


class BienvenidaView(LoginRequiredMixin, TemplateView):
    success_url = reverse_lazy('bienvenida')
    template_name = 'bienvenida.html'


class LoginView(LoginView):
    success_url = reverse_lazy('usuarios:home')
    template_name = 'login.html'
    form_class = AuthenticationForm


class LoginViewAlumno(LoginView):
    success_url = reverse_lazy('home_alumno')
    template_name = 'login_alumno.html'
    form_class = AuthenticationForm


@login_required
def home(request):
    if request.user.is_staff:
        return render(request, 'home_case.html')
    else:
        return redirect('usuarios:home_alumno')


@login_required
def homeAlumno(request):
    if not request.user.is_superuser and not request.user.is_staff:
        return render(request, 'index_alumno.html')
    else:
        return redirect('usuarios:home')


def error404(request):
    return render(request, '404.html')


class RegistrarAdmin(LoginRequiredMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = 'registro_de_administrador.html'
    success_url = reverse_lazy('usuarios:login')
    success_message = "%(username)s se registró de manera exitosa"

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.is_superuser = True
        user.is_staff = True
        user.save()
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('usuarios:login'))


class RegistrarAdminCASE(LoginRequiredMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = 'registro_admin_case.html'
    success_url = reverse_lazy('usuarios:home')
    success_message = "%(username)s se registró de manera exitosa"

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.is_superuser = True
        user.is_staff = True
        user.save()
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('usuarios:home'))


@login_required
def lista_admins(request):
    if request.user.is_superuser:
        administradores = User.objects.filter(is_superuser=True)
        return render(request, 'administradores.html', {'administradores': administradores})
    else:
        if request.user.is_staff:
            return redirect('usuarios:home')
        else:
            return redirect('usuarios:home_alumno')


@login_required
def lista_alumnos(request):
    if request.user.is_staff:
        user_alumno = Alumnos.objects.all()
        return render(request, 'alumnos.html', {'alumnos': user_alumno})
    return redirect('usuarios:home_alumno')
    


@login_required
def lista_responsables(request):
    if request.user.is_superuser:
        user_responsable = Responsables.objects.all()
        return render(request, 'responsables.html', {'responsables': user_responsable})
    else:
        if request.user.is_staff:
            return redirect('usuarios:home')
        else:
            return redirect('usuarios:home_alumno')


class RegistrarAlumno(LoginRequiredMixin, CreateView):
    model = Alumnos
    form_class = AlumnoForm
    template_name = 'registro_alumno.html'
    success_url = reverse_lazy('usuarios:home')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.is_superuser = False
        user.is_staff = False
        user.save()
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('usuarios:home'))


class RegistrarResponsable(LoginRequiredMixin, CreateView):
    model = Responsables
    form_class = ResponsableForm
    template_name = 'registro_responsable.html'
    success_url = reverse_lazy('usuarios:home')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.is_superuser = False
        user.is_staff = True
        user.save()
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('usuarios:home'))

# Función para cerrar sesión/SI SE OCUPA NO BORRAR


@login_required
def signout(request):
    if request.user.is_staff:
        logout(request)
        return redirect('usuarios:login')
    else:
        logout(request)
        return redirect('usuarios:login_alumno')

trayectoriaescolar/usuarios/templates/bienvenida.html
{% extends 'home_case.html' %}

{% block titulo %}
    Bienvenido al sistema de SSTE
{% endblock titulo %}

{% block contenido %}
    <h2>{{user}} bienvenido al Sistema de Seguimiento de Trayectoria Escolar CASE</h2>
{% endblock %}

trayectoriaescolar/usuarios/templates/responsables.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Table - Brand</title>
    <link rel="stylesheet" href="{% static 'dist/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;display=swap">
    <link rel="stylesheet" href="{% static 'dist/fonts/fontawesome-all.min.css' %}">
</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
            <div class="container-fluid d-flex flex-column p-0">
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar"></ul>
                <div class="text-center d-none d-md-inline"></div>
                <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0" style="background: #26344d;">
                    <div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#"><img style="background: url(&quot;static/dist/img/dogs/trayectoriaescolar.pngs&quot;);position: absolute;margin-top: 1cm;" src="static/dist/img/dogs/trayectoriaescolar.png" width="130" height="130">
                            <div class="sidebar-brand-icon rotate-n-15"></div>
                            <div class="sidebar-brand-text mx-3"></div>
                        </a>
                        <hr class="sidebar-divider my-0">
                        <ul class="navbar-nav text-light" id="accordionSidebar-1">
                            <li class="nav-item"><a class="nav-link" href="{% url 'usuarios:home'%}" style="margin-top: 2cm;"><i class="fas fa-home"></i><span>&nbsp;Inicio</span></a></li>
                            <hr class="sidebar-divider">
                            <div class="sidebar-heading">
                                <p class="mb-0">Administrar</p>
                            </div>
                            <li class="nav-item">
                                <div><a class="btn btn-link nav-link" data-bs-toggle="collapse" aria-expanded="true" aria-controls="collapse-1" href="#collapse-1" role="button"><i class="fas fa-users"></i>&nbsp;<span>Registros</span></a>
                                    <div class="collapse show" id="collapse-1">
                                        <div class="bg-white border rounded py-2 collapse-inner">
                                            <h6 class="collapse-header">Registrar</h6><a class="collapse-item" href="{% url 'usuarios:registro_admin_case'%}"><i class="fas fa-user-lock"></i>Administradores</a><a class="collapse-item" href="{% url 'usuarios:registro_responsable'%}"><i class="fas fa-user-tie"></i>Responsables</a><a class="collapse-item" href="{% url 'usuarios:registro_alumno'%}"><i class="fas fa-user-graduate"></i>Alumnos</a>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item">
                                <div><a class="btn btn-link nav-link" data-bs-toggle="collapse" aria-expanded="true" aria-controls="collapse-2" href="#collapse-2" role="button"><i class="fas fa-user-friends"></i>&nbsp;<span>Usuarios</span></a>
                                    <div class="collapse show" id="collapse-2">
                                        <div class="bg-white border rounded py-2 collapse-inner">
                                            <h6 class="collapse-header">Listar</h6><a class="collapse-item" href="administradores"><i class="fas fa-user-lock"></i>Administradores</a><a class="collapse-item" href="responsables"><i class="fas fa-user-tie"></i>Responsables</a><a class="collapse-item" href="alumnos"><i class="fas fa-user-graduate"></i>Alumnos</a>
                                        </div>
                                    </div>
                                </div>
                                <div><a class="btn btn-link nav-link" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapse-4" href="#collapse-4" role="button"><i class="fas fa-file-alt"></i>&nbsp;<span>Crear encuesta</span></a>
                                    <div class="collapse" id="collapse-4">
                                        <div class="bg-white border rounded py-2 collapse-inner"><a class="collapse-item" href="utilities-color.html">Encuesta de seguimiento</a><a class="collapse-item" href="utilities-border.html">Encuesta2</a><a class="collapse-item" href="utilities-animation.html">Encuesta3</a><a class="collapse-item" href="utilities-other.html">Encuesta3</a></div>
                                    </div>
                                </div>
                            </li>
                            <hr class="sidebar-divider">
                            <div class="sidebar-heading">
                                <p class="mb-0">Otros</p>
                            </div>
                            <li class="nav-item">
                                <div><a class="btn btn-link nav-link" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapse-3" href="#collapse-3" role="button"><i class="fas fa-folder"></i>&nbsp;<span>Generar</span></a>
                                    <div class="collapse" id="collapse-3">
                                        <div class="bg-white border rounded py-2 collapse-inner">
                                            <h6 class="collapse-header">LOGIN SCREENS:</h6><a class="collapse-item" href="login_admin.html">Fichas de alumnos</a><a class="collapse-item" href="register.html">Gráficas de encuestas</a>
                                        </div>
                                    </div>
                                </div>
                                <div id="collapsePages" class="collapse" aria-labelledby="headingTwo" aria-controls="collapsePages" data-bs-parent="#accordionSidebar">
                                    <div class="bg-white border rounded py-2 collapse-inner">
                                        <h6 class="collapse-header">LOGIN SCREENS:</h6><a class="collapse-item" href="#">Login</a><a class="collapse-item" href="#">Register</a><a class="collapse-item" href="#">Forgot Password</a>
                                        <h6 class="collapse-header">OTHER PAGES:</h6><a class="collapse-item" href="#">404 Page</a><a class="collapse-item" href="#">Blank Page</a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="charts.html"><i class="fas fa-book-open"></i><span>Servicios</span></a></li>
                            <li class="nav-item"></li>
                            <hr class="sidebar-divider">
                        </ul><a class="btn btn-primary" href="{% url 'usuarios:logout'%}" type="button" style="background: var(--bs-btn-hover-color);color: rgb(255,0,0);">Salir</a>
                        <div class="text-center d-none d-md-inline"></div>
                    </div>
                </nav>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid"><a class="btn btn-light btn-icon-split" role="button"></a></div>
                </nav>
                <div class="container-fluid">
                    <h3 class="text-dark mb-4">Datos de Responsables de Programas</h3>
                    <div class="card shadow">
                        
                        <div class="card-header py-3">
                            <button class="btn btn-primary" type="button" style="background-color: rgb(35,42,53);">Agregar nuevo Responsable</button>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 text-nowrap">
                                    <div id="dataTable_length" class="dataTables_length" aria-controls="dataTable"></div>
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-end dataTables_filter" id="dataTable_filter"><label class="form-label"></label></div>
                                </div>
                            </div>
                            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Segundo Nombre</th>
                                        <th>Primer apellido</th>
                                        <th>Segundo apellido</th>
                                        <th>Correo</th>
                                        <th>Programa Academico</th>
                                        <th>Unidad Academica</th>
                                        <th scope="col">Editar</th>
                                        <th scope="col">Eliminar</th>


                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for responsable in responsables %}
                                    <tr>
                                        <td>{{responsable.nombre}}</td>
                                        <td>{{responsable.nombre2}}</td>
                                        <td>{{responsable.apellidoP}}</td>
                                        <td>{{responsable.apellidoM}}</td>
                                        <td>{{responsable.email}}</td>
                                        <td>{{responsable.programa_academico}}</td>
                                        <td>{{responsable.unidad_academica}}</td>
                                        <td><a class= "btn btn-warning" href="#"> Editar </td>
                                        <td><a class= "btn btn-danger" href="#"> Eliminar </td>

                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>© Centro de Aprendizaje y Servicios Estudiantiles CASE&nbsp;</span></div>
                </div>
            </footer>
    </div>
    <script src="{% static 'dist/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'dist/js/theme.js' %"></script>
</body>

</html>